# Generated by Django 4.0.6 on 2022-07-30 10:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('cover_type', models.CharField(choices=[('softcover', 'Softcover'), ('hardcover', 'Hardcover')], max_length=9)),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('percentage_discount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=100)])),
                ('total_quantity', models.PositiveSmallIntegerField()),
                ('barcode', models.CharField(max_length=13)),
                ('isbn', models.CharField(max_length=13)),
                ('year_of_print', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('number_of_page', models.CharField(max_length=50)),
                ('detail', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='book/image/%Y-%m-%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='product.bookcategory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
